name: joomla
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.0.0
  smooth_page_indicator: ^1.1.0
  icon_broken: ^1.1.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  conditional_builder_null_safety: ^0.0.6
  alert_dialog: ^1.0.1
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  get: ^4.6.5
  shimmer: ^3.0.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/on4.jpg
    - assets/images/on.jpeg
    - assets/images/on3.jpg
    - assets/images/f.png
    - assets/images/g.png
    - assets/images/t.png
    - assets/images/back.jpg
    - assets/images/empty.gif
    - assets/images/loading.gif
    - assets/images/ahmed.jpg


  uses-material-design: true

